src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Repository\InvoiceRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=InvoiceRepository::class)
 */
class Invoice
{
    public const VAT_PERCENTAGE = 20;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $designation;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $description;

    /**
     * @ORM\Column(type="decimal", precision=7, scale=2)
     * @Assert\NotBlank
     */
    private $priceBeforeVat;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPriceBeforeVat(): ?string
    {
        return $this->priceBeforeVat;
    }

    public function setPriceBeforeVat(string $priceBeforeVat): self
    {
        $this->priceBeforeVat = $priceBeforeVat;

        return $this;
    }

    public function getVatAmount(): ?float
    {
        return $this->priceBeforeVat * self::VAT_PERCENTAGE / 100;
    }

    public function getPriceAfterVat(): ?float
    {
        return $this->priceBeforeVat + $this->getVatAmount();
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/InvoiceType.php
<?php

namespace App\Form;

use App\Entity\Invoice;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InvoiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('designation', null, [
                    'label' => 'Désignation',
                ])
                ->add('description')
                ->add('priceBeforeVat', null, [
                    'label' => 'Prix HT',
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Invoice::class,
        ]);
    }
}

src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use App\Entity\Invoice;
use App\Form\InvoiceType;
use App\Repository\InvoiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/invoice")
 * @IsGranted("ROLE_USER")
 */
class InvoiceController extends AbstractController
{
    public const ITEMS_PER_PAGE = 5;

    /**
     * @var Security
     */
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * @Route("/", name="invoice_index", methods={"GET"})
     */
    public function index(InvoiceRepository $invoiceRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $user = $this->security->getUser();

        $invoices = $paginator->paginate(
            $invoiceRepository->findByUser($user), 
            $request->query->getInt('page', 1), 
            self::ITEMS_PER_PAGE
        );

        return $this->render('invoice/index.html.twig', [
            'invoices' => $invoices,
        ]);
    }

    /**
     * @Route("/new", name="invoice_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $invoice = new Invoice();
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $invoice->setUser($this->getUser());
            $entityManager->persist($invoice);
            $entityManager->flush();

            return $this->redirectToRoute('invoice_index');
        }

        return $this->render('invoice/new.html.twig', [
            'invoice' => $invoice,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="invoice_show", methods={"GET"})
     */
    public function show(Invoice $invoice): Response
    {
        return $this->render('invoice/show.html.twig', [
            'invoice' => $invoice,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="invoice_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Invoice $invoice): Response
    {
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('invoice_index');
        }

        return $this->render('invoice/edit.html.twig', [
            'invoice' => $invoice,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="invoice_delete", methods={"POST"})
     */
    public function delete(Request $request, Invoice $invoice): Response
    {
        if ($this->isCsrfTokenValid('delete'.$invoice->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($invoice);
            $entityManager->flush();
        }

        return $this->redirectToRoute('invoice_index');
    }
}

templates/invoice/_delete_form.html.twig
<form method="post" action="{{ path('invoice_delete', {'id': invoice.id}) }}" class="d-inline" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cet élément?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ invoice.id) }}">
    <button class="btn bg-transparent p-0"><i class="far fa-trash-alt text-danger"></i></button>
</form>

templates/invoice/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/invoice/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Factures - Modification{% endblock %}

{% block body %}
    <h4 class="mb-4">Modification d'une facture</h4>

    {{ include('invoice/_form.html.twig', {'button_label': 'Enregistrer'}) }}

{% endblock %}

templates/invoice/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Factures - liste{% endblock %}

{% block body %}
    <h4>Liste des factures</h4>
    <a href="{{ path('invoice_new') }}" class="btn btn-outline-primary mb-3">Créer une nouvelle facture</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">N°</th>
                <th scope="col">Désignation</th>
                <th scope="col">Prix HT</th>
                <th scope="col">TVA</th>
                <th scope="col">Prix TTC</th>
                <th scope="col text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for invoice in invoices %}
                <tr>
                    <th scope="row">
                        <a href="{{ path('invoice_show', {'id': invoice.id}) }}">#{{ invoice.id }}</a>
                    </th>
                    <td>{{ invoice.designation }}</td>
                    <td>{{ invoice.priceBeforeVat }}</td>
                    <td>{{ invoice.vatAmount }}</td>
                    <td>{{ invoice.priceAfterVat }}</td>
                    <td class="text-center">
                        <a href="{{ path('invoice_edit', {'id': invoice.id}) }}"><i class="far fa-edit text-success"></i></a>
                        {{ include('invoice/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">Les liste des factures ne contient aucun élément pour l'instant.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="d-flex justify-content-center">
        {{ knp_pagination_render(invoices) }}
    </div>
{% endblock %}

templates/invoice/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Factures - Création{% endblock %}

{% block body %}
    <h4 class="mb-4">Création d'une nouvelle facture</h4>

    {{ include('invoice/_form.html.twig') }}
{% endblock %}

templates/invoice/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Factures - Consultation{% endblock %}

{% block body %}
    <h4 class="mb-4">Consultation d'une facture</h4>

    <table class="table">
        <tbody>
            <tr>
                <th>N°</th>
                <td>{{ invoice.id }}</td>
            </tr>
            <tr>
                <th>Désignation</th>
                <td>{{ invoice.designation }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ invoice.description }}</td>
            </tr>
            <tr>
                <th>Prix HT</th>
                <td>{{ invoice.priceBeforeVat }}</td>
            </tr>
            <tr>
                <th>TVA</th>
                <td>{{ invoice.vatAmount }}</td>
            </tr>
            <tr>
                <th>Prix TTC</th>
                <td>{{ invoice.priceAfterVat }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('invoice_edit', {'id': invoice.id}) }}"><i class="far fa-edit text-success"></i></a>

    {{ include('invoice/_delete_form.html.twig') }}
{% endblock %}